const defaultRooms=[{id:1,title:"Furnished Single Room",area:"Whitefield, Bengaluru",rent:7500,deposit:15000,type:"Single Room",img:"https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80",fac:["Wi-Fi","Attached Bathroom","Parking"],phone:"919876543210",desc:"Clean furnished room close to offices and public transport.",verified:true},{id:2,title:"Modern PG for Working Professionals",area:"HSR Layout, Bengaluru",rent:9000,deposit:18000,type:"PG",img:"https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",fac:["Wi-Fi","AC","Food"],phone:"919876543211",desc:"Comfortable PG with modern facilities.",verified:true},{id:3,title:"Affordable Shared Room",area:"Electronic City, Bengaluru",rent:5000,deposit:10000,type:"Shared Room",img:"https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=900&q=80",fac:["Wi-Fi","Parking"],phone:"919876543212",desc:"Budget-friendly shared room near IT parks.",verified:false},{id:4,title:"Cozy 1BHK Apartment",area:"Marathahalli, Bengaluru",rent:12500,deposit:25000,type:"1BHK",img:"https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=900&q=80",fac:["AC","Attached Bathroom","Parking"],phone:"919876543213",desc:"Private 1BHK suitable for working professionals.",verified:true},{id:5,title:"Budget Single Room",area:"Koramangala, Bengaluru",rent:8500,deposit:17000,type:"Single Room",img:"https://images.unsplash.com/photo-1564078516393-cf04bd966897?auto=format&fit=crop&w=900&q=80",fac:["Wi-Fi","Attached Bathroom"],phone:"919876543214",desc:"Good location with shops and cafes nearby.",verified:false},{id:6,title:"Girls PG — Near Metro",area:"Indiranagar, Bengaluru",rent:10000,deposit:20000,type:"PG",img:"https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=900&q=80",fac:["Wi-Fi","AC","Food"],phone:"919876543215",desc:"PG with easy access to metro and daily essentials.",verified:true}];
let rooms=JSON.parse(localStorage.getItem("roomlyRooms")||"null")||defaultRooms,filtered=[...rooms];
const saved=()=>JSON.parse(localStorage.getItem("roomlySaved")||"[]").map(Number);
const safe=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function card(r){let p=String(r.phone||"").replace(/\D/g,""),wa=`https://wa.me/${p}?text=${encodeURIComponent("Hi, I found your room on Roomly: "+r.title+" in "+r.area+". Is it available?")}`,sv=saved().includes(Number(r.id));return `<article class="card"><img src="${safe(r.img||defaultRooms[0].img)}" alt="${safe(r.title)}" onclick="openRoom(${r.id})" onerror="this.src='${defaultRooms[0].img}'"><div class="card-body"><div class="muted">${safe(r.type)}${r.verified?" • ✓ Verified":""}</div><h3>${safe(r.title)}</h3><div class="muted">📍 ${safe(r.area)}</div><p class="price">₹${Number(r.rent).toLocaleString("en-IN")} <small>/month</small></p><div class="tags">${(r.fac||[]).map(x=>`<span class="tag">${safe(x)}</span>`).join("")}</div><p class="muted">${safe(r.desc||"")}</p><div class="actions"><a class="wa" target="_blank" href="${wa}">💬 WhatsApp</a><button class="save" onclick="saveRoom(${r.id})">${sv?"♥ Saved":"♡ Save"}</button><button class="call" onclick="callOwner('${p}')">📞</button></div></div></article>`}
function render(){let s=document.getElementById("sort").value,list=[...filtered].sort((a,b)=>s==="low"?a.rent-b.rent:s==="high"?b.rent-a.rent:0);document.getElementById("roomGrid").innerHTML=list.length?list.map(card).join(""):"<p class='muted'>No matching rooms found. Try changing filters.</p>";document.getElementById("resultText").textContent=`${list.length} room${list.length!==1?"s":""} found`;renderSaved()}
function renderSaved(){let ids=saved(),list=rooms.filter(r=>ids.includes(Number(r.id)));document.getElementById("savedGrid").innerHTML=list.length?list.map(card).join(""):"<p class='muted'>No saved rooms yet. Tap ♡ Save on a room you like.</p>"}
function searchRooms(){let l=locationEl().toLowerCase().trim(),max=Number(document.getElementById("maxRent").value)||Infinity,t=document.getElementById("type").value,fs=[...document.querySelectorAll(".facility:checked")].map(x=>x.value);filtered=rooms.filter(r=>(!l||r.area.toLowerCase().includes(l)||r.title.toLowerCase().includes(l))&&r.rent<=max&&(!t||r.type===t)&&fs.every(f=>(r.fac||[]).includes(f)));render();document.getElementById("rooms").scrollIntoView({behavior:"smooth"})}
function locationEl(){return document.getElementById("location").value}
function clearFilters(){document.getElementById("location").value="";document.getElementById("maxRent").value="";document.getElementById("type").value="";document.querySelectorAll(".facility").forEach(x=>x.checked=false);filtered=[...rooms];render()}
function saveRoom(id){let a=saved(),n=Number(id);a=a.includes(n)?a.filter(x=>x!==n):[...a,n];localStorage.setItem("roomlySaved",JSON.stringify(a));render()}
function callOwner(p){if(p)location.href="tel:"+p}
function openRoom(id){let r=rooms.find(x=>Number(x.id)===Number(id));if(!r)return;modalImg.src=r.img||defaultRooms[0].img;modalTitle.textContent=r.title;modalType.textContent=r.type+(r.verified?" • ✓ Verified":"");modalArea.textContent="📍 "+r.area;modalPrice.innerHTML="₹"+Number(r.rent).toLocaleString("en-IN")+" <small>/month</small>";modalTags.innerHTML=(r.fac||[]).map(x=>`<span class="tag">${safe(x)}</span>`).join("");modalDesc.textContent=r.desc||"";modalDeposit.textContent=r.deposit?"Security deposit: ₹"+Number(r.deposit).toLocaleString("en-IN"):"";let p=String(r.phone||"").replace(/\D/g,"");modalWa.href=`https://wa.me/${p}?text=${encodeURIComponent("Hi, I found your room on Roomly: "+r.title+" in "+r.area+". Is it available?")}`;modalCall.onclick=()=>callOwner(p);modalSave.onclick=()=>{saveRoom(r.id);modalSave.textContent=saved().includes(Number(r.id))?"♥ Saved":"♡ Save"};modalSave.textContent=saved().includes(Number(r.id))?"♥ Saved":"♡ Save";document.getElementById("modal").classList.add("open")}
function closeModal(e){if(!e||e.target.id==="modal")document.getElementById("modal").classList.remove("open")}
function toggleTheme(){document.body.classList.toggle("dark");localStorage.setItem("roomlyTheme",document.body.classList.contains("dark")?"dark":"light");themeBtn.textContent=document.body.classList.contains("dark")?"☀️":"🌙"}
document.getElementById("listingForm").addEventListener("submit",e=>{e.preventDefault();let r={id:Date.now(),title:fTitle.value.trim(),area:fArea.value.trim(),rent:Number(fRent.value),deposit:Number(fDeposit.value)||0,type:fType.value,img:fImage.value.trim(),phone:fPhone.value.trim(),fac:fFacilities.value.split(",").map(x=>x.trim()).filter(Boolean),desc:fDesc.value.trim(),verified:false};rooms.unshift(r);localStorage.setItem("roomlyRooms",JSON.stringify(rooms));filtered=[...rooms];render();e.target.reset();alert("✅ Listing published successfully!")});
if(localStorage.getItem("roomlyTheme")==="dark")document.body.classList.add("dark");render();
